import React from 'react';

import './lorem-ipsum.css';

const LoremIpsum = () => (
  <div className="lorem-ipsum">
    <div>Lorem ipsum blandit magna platea lorem tempor senectus nibh lacus pretium, vivamus commodo feugiat interdum aliquam mi semper etiam nostra mattis auctor, sagittis potenti vivamus tincidunt viverra lacinia mattis massa ultricies urna interdum diam vel quis fames ad et ante conubia leo per, faucibus eu faucibus felis justo donec fusce primis taciti in purus vel mollis leo nullam consectetur dolor amet consequat gravida, eleifend nisi urna malesuada congue curabitur torquent maecenas fermentum iaculis tempus donec sapien per auctor adipiscing etiam ullamcorper quisque, suspendisse dolor felis primis posuere himenaeos auctor praesent massa, magna scelerisque sagittis pretium rhoncus vulputate ut molestie duis.</div>
    <div>Inceptos ornare lacinia iaculis senectus lectus sociosqu aliquet metus mauris pretium cras, urna dui mi odio vel nullam odio purus elementum scelerisque urna, ornare cras quisque varius dapibus tortor nullam vitae est blandit nam justo posuere nisl volutpat integer nec donec nulla arcu, phasellus in feugiat placerat tempor magna ut malesuada justo, commodo malesuada hac nisl eros pretium dapibus metus imperdiet libero erat congue dolor porta in cursus volutpat etiam vivamus nostra nisl praesent potenti ad curae, donec ut interdum habitasse interdum nisl inceptos accumsan tellus at torquent dapibus interdum sagittis varius litora non adipiscing ipsum sed mi nibh euismod.</div>
    <div>Nisi purus id accumsan lacinia velit nisl ut diam, vel suscipit nisi hendrerit suspendisse ligula donec, himenaeos per ac elit senectus ante arcu turpis quisque quis ante a consequat porttitor rutrum phasellus amet tempor, proin aenean augue volutpat potenti quis justo luctus eget laoreet himenaeos iaculis sit lacinia erat sagittis maecenas litora ultricies phasellus netus blandit urna scelerisque luctus nec, ipsum lacinia purus aliquet ut massa curabitur leo aliquam mattis tortor curae ligula donec felis praesent iaculis dui consequat habitasse, ullamcorper sit feugiat eu curabitur, libero quis lacus conubia ut fames faucibus eget commodo laoreet per semper ultricies fringilla aliquet.</div>
    <div>Taciti habitasse venenatis sollicitudin luctus rutrum facilisis scelerisque orci netus, libero ligula praesent adipiscing varius vehicula auctor cubilia, tellus scelerisque dui orci duis auctor sem curabitur eu venenatis integer rutrum donec aenean dui id luctus aliquam, interdum bibendum class felis eu donec ultricies a aenean, iaculis libero diam cursus tellus curae praesent malesuada viverra vivamus lectus id purus nisi pellentesque a himenaeos, adipiscing et urna conubia nam volutpat pellentesque, quisque odio justo integer senectus tincidunt dictumst cursus faucibus egestas torquent dictum facilisis iaculis litora accumsan, tortor maecenas in posuere conubia pharetra proin sem, volutpat ac nam gravida sapien blandit hendrerit.</div>
    <div>Aliquam lobortis rhoncus odio dictumst magna mi molestie ultricies, sodales ad per curae fermentum at purus vitae neque, velit rutrum elementum fringilla tempor bibendum metus congue augue per dui volutpat bibendum lacus, sollicitudin purus lobortis netus quis magna, lacinia duis egestas primis rhoncus laoreet volutpat platea praesent tellus torquent nam venenatis, neque sit pretium magna justo semper cras, lobortis etiam fringilla scelerisque varius erat interdum lobortis fermentum curabitur tempus ut magna et, varius mi nunc pulvinar porta ut, conubia nisl integer eros ligula lobortis massa blandit ut mollis aenean nisl, integer placerat elit vestibulum tellus aliquam, turpis convallis platea conubia.</div>
    <div>Facilisis felis bibendum dictum non fusce turpis urna, aliquam suspendisse accumsan eget netus mollis, quisque feugiat integer leo torquent maecenas elit integer duis suscipit quam ipsum phasellus diam consectetur taciti curabitur id, malesuada posuere vitae lacus sociosqu cubilia habitasse per integer elit consectetur, eleifend phasellus iaculis magna mauris mollis nostra feugiat et sem platea facilisis torquent semper auctor torquent dui hac consequat quisque, justo maecenas sit sollicitudin consectetur curabitur urna sodales diam, potenti semper aliquet venenatis leo netus dolor elit curabitur nibh cras conubia lacinia nunc vel iaculis, est fringilla condimentum lectus sodales semper, felis turpis massa libero adipiscing eleifend.</div>
    <div>Curabitur arcu convallis donec potenti etiam urna, conubia euismod torquent molestie odio ligula sodales, convallis et vivamus blandit enim ultrices lorem proin sociosqu euismod praesent pellentesque per, eget litora sociosqu leo inceptos diam eleifend sit, curae etiam odio primis vestibulum pellentesque molestie lectus leo egestas posuere adipiscing platea, tristique blandit ligula sem ut maecenas massa, vehicula ligula mollis ligula porta mattis ligula phasellus commodo nisi metus netus nibh ad amet, nullam inceptos pharetra ornare scelerisque enim fringilla proin litora cubilia, nullam adipiscing consectetur himenaeos est donec sagittis euismod aenean consectetur curabitur hac etiam placerat vehicula convallis odio aenean proin tempor.</div>
    <div>Dapibus fusce mauris bibendum phasellus facilisis duis diam, suscipit varius euismod class lacus lacinia, egestas velit nibh vehicula accumsan cras facilisis proin tristique consequat euismod est massa litora quisque, nisl inceptos mollis curabitur dictumst diam bibendum aliquet, ligula posuere cubilia aliquet aliquam interdum quisque nam netus sem fermentum nostra quam viverra cras duis, tristique etiam inceptos sem eleifend nisl commodo, viverra consectetur dictum ornare netus porttitor sollicitudin nam ligula curae turpis platea non habitant a porta, turpis congue tortor hac luctus curabitur rutrum, aliquam aenean placerat rhoncus netus facilisis senectus nisi duis adipiscing hendrerit aenean sed ac torquent pellentesque sagittis.</div>
    <div>Laoreet vestibulum elit suspendisse varius primis vehicula pretium, facilisis fusce phasellus tellus congue ante curabitur malesuada, class et posuere suscipit ultricies dui semper, orci ultrices facilisis ornare justo scelerisque feugiat bibendum ante ullamcorper velit ornare cursus porttitor sollicitudin ut vel interdum quisque sollicitudin lacus aenean phasellus scelerisque lorem est, elit imperdiet id placerat sollicitudin suspendisse, curae suscipit aenean porta lacus habitant risus pellentesque porttitor ultricies ac tellus, pulvinar ligula nisl convallis integer tristique rhoncus ad, nam donec aliquam ipsum elit consectetur at ultricies iaculis per pharetra est molestie cras erat per porta, ultrices libero auctor viverra aptent nec ultrices primis.</div>
    <div>Leo fames curae taciti phasellus torquent varius pellentesque, curabitur vestibulum leo mauris posuere non leo pretium, et adipiscing vestibulum magna laoreet inceptos quisque gravida varius placerat fringilla justo cubilia curabitur risus pellentesque aliquet ante nulla vulputate purus donec suspendisse litora conubia aptent sed pulvinar odio nec platea, quis pretium curabitur id nunc augue rhoncus nunc nisi, tempus pellentesque conubia augue facilisis massa luctus aliquam per etiam torquent nisl morbi fames eros sed consectetur metus gravida, sollicitudin neque praesent habitasse odio fusce at lacus, a torquent interdum ut taciti fusce at curabitur lorem fringilla lectus viverra himenaeos potenti fames sem quisque.</div>
    <div>Sodales mi ante semper viverra eleifend tempus rhoncus, fringilla dolor aenean odio scelerisque hac justo fusce, sit rutrum turpis scelerisque elementum egestas fusce euismod venenatis proin massa quis interdum adipiscing, ad interdum donec fusce potenti lacus amet, condimentum placerat at suspendisse commodo risus nisl lacus feugiat suscipit tristique nam sit netus tellus, cursus elit imperdiet sem pharetra elit curabitur ornare pharetra, condimentum suspendisse etiam venenatis sed malesuada rutrum hac condimentum fringilla augue lacus in pellentesque fermentum scelerisque primis nunc lorem, nibh malesuada blandit torquent neque molestie porttitor ligula adipiscing maecenas, taciti tristique habitasse aptent varius massa habitasse porta tempor imperdiet.</div>
    <div>Laoreet ultricies conubia amet erat mi orci ultricies ligula convallis habitasse eros class eros elementum per ut, blandit est lacinia convallis etiam feugiat habitant sodales consequat fusce orci ipsum facilisis aliquam orci ullamcorper scelerisque platea curabitur condimentum cursus iaculis mattis litora turpis imperdiet, et faucibus nisi sodales viverra curae praesent etiam sem rhoncus quisque, diam curabitur nibh facilisis eros lacus faucibus cras eros per eget sapien diam amet inceptos quis quisque arcu ut nullam sit vehicula, molestie duis velit fringilla phasellus cursus ultrices elit quam mi mollis tempus quisque nibh urna est ad fusce ac amet ad senectus aliquam nulla.</div>
    <div>Donec etiam turpis metus senectus urna ac potenti, cursus in posuere mollis mi quisque nisl aliquam, nostra ultrices nisi rutrum porttitor suspendisse pharetra nisi dolor ligula proin molestie platea quisque consectetur non, malesuada ut himenaeos diam urna diam etiam pharetra, massa duis cursus lobortis quisque eleifend fames condimentum lobortis sapien augue ad pharetra interdum velit ante viverra vestibulum ad ac, cursus tristique ac dui id feugiat id quisque ultricies curae, netus potenti sollicitudin curabitur vulputate platea rutrum urna hendrerit euismod nibh nam fringilla sem class maecenas hendrerit dui, blandit quis litora inceptos dictumst blandit, nec eleifend neque aliquam quis mi.</div>
    <div>In quam congue blandit senectus erat ut morbi faucibus, pellentesque magna elementum fusce commodo donec condimentum aliquam, nulla diam sem feugiat tellus quisque sit vestibulum lacus in sed et magna molestie class faucibus, leo fermentum justo pretium et vestibulum lacinia class quisque, diam nisl euismod lorem tincidunt convallis lacinia varius justo himenaeos sollicitudin sed pharetra cubilia donec nam adipiscing consectetur primis donec, ultricies nec ante viverra gravida curabitur rutrum luctus turpis tellus iaculis taciti, aptent auctor metus torquent urna gravida justo consequat rhoncus dapibus suspendisse eros dolor scelerisque amet suscipit proin, id bibendum donec nibh aliquet, platea donec a amet.</div>
    <div>Fringilla curabitur vitae molestie odio amet urna maecenas class mi maecenas, donec massa eget interdum velit lacinia varius odio lorem, pharetra quam enim non in sagittis elit metus viverra nostra per faucibus placerat purus accumsan consequat bibendum quisque vestibulum ipsum leo vivamus lacinia amet, dictumst aliquam facilisis odio ante ut consectetur enim habitant lacus etiam suspendisse auctor, scelerisque venenatis id pretium neque cursus platea himenaeos at fringilla pulvinar placerat netus rhoncus libero pulvinar euismod rhoncus elementum dolor molestie mauris, fringilla condimentum vitae velit est orci pellentesque, lacinia quisque fusce magna eros enim leo primis gravida tempus convallis pretium dictum nullam.</div>
    <div>Ac aenean tempor neque vulputate turpis at urna imperdiet donec curabitur, accumsan sodales habitasse erat fermentum nam vulputate dolor viverra, morbi fames nec cursus elementum aliquet rutrum mattis aenean tempus sodales tempus tellus in dui gravida, vitae accumsan egestas semper nullam arcu, nisi congue risus sagittis feugiat fames interdum feugiat habitant turpis per ultrices sapien, taciti rhoncus porta tristique tellus tempus enim, nisl dapibus praesent eget proin velit a rutrum mauris neque ligula adipiscing nibh, hendrerit nostra fames metus hac donec, sollicitudin id ante aliquam litora neque ante aliquet feugiat duis tortor in viverra suspendisse ut dictum ultrices consectetur blandit.</div>
    <div>Himenaeos at placerat tincidunt integer vestibulum pharetra, nulla nunc curae nisl tempor integer, porta luctus turpis vehicula cubilia pellentesque commodo nec curabitur curae in mattis potenti fusce, lectus eu a netus imperdiet cursus curabitur, tempor et bibendum amet quisque potenti justo inceptos himenaeos inceptos orci eros ornare primis hendrerit ad, facilisis pretium lorem class phasellus dictumst nisl, nisi pulvinar ullamcorper eu lacinia curae consequat metus ligula pharetra est euismod gravida interdum netus cubilia, interdum conubia luctus ornare quisque curabitur nullam semper, laoreet vehicula magna scelerisque vulputate pellentesque per fames sed vulputate mattis porttitor fermentum proin fermentum nibh metus neque velit.</div>
    <div>Sagittis mauris viverra phasellus velit sit inceptos non netus per, hendrerit auctor praesent blandit vivamus quisque ornare platea tempor quisque, enim ante litora tempor luctus vestibulum et sodales himenaeos hac quis sapien tempor luctus elit tempus quisque turpis feugiat adipiscing, netus rhoncus id non per sollicitudin ultricies felis nisi tempus ac vehicula, tempus urna porttitor congue ultricies quisque commodo aliquam bibendum cras sem praesent aliquam suspendisse at leo mattis vivamus amet metus nec, arcu vitae duis nostra malesuada sed fusce phasellus sodales senectus posuere faucibus lorem placerat phasellus sem, vestibulum habitasse pharetra consequat condimentum ultricies, inceptos laoreet morbi imperdiet accumsan.</div>
    <div>Lorem sed ipsum etiam turpis urna facilisis vivamus posuere dictum ac, vitae morbi erat curabitur praesent consequat sollicitudin inceptos amet sed a, ipsum habitant morbi porta nunc mauris ad cursus venenatis cras commodo venenatis justo aptent himenaeos urna eget tristique faucibus etiam nisl potenti tristique mattis eu hendrerit leo praesent vulputate, lorem potenti etiam est semper ultrices, turpis in pellentesque feugiat integer vitae proin vivamus phasellus platea nisl taciti habitant suscipit nisl, auctor inceptos etiam morbi ultrices per habitant hendrerit, erat malesuada scelerisque consectetur himenaeos aptent sapien donec non metus ut dapibus taciti nam sollicitudin fames tincidunt cras nullam dui.</div>
    <div>Ultricies malesuada nam diam lectus faucibus odio egestas himenaeos, venenatis non id arcu lobortis consectetur scelerisque ante, etiam porta id suscipit cubilia elit egestas inceptos platea sodales mollis commodo mollis elit proin bibendum tortor, per est lacus aenean nibh conubia hendrerit habitant odio, ultricies laoreet curabitur iaculis posuere suspendisse consectetur placerat urna hendrerit pretium ullamcorper volutpat justo eget quis quisque vel habitant, mollis sodales netus etiam ante convallis quisque etiam tellus venenatis eget netus sociosqu ultrices augue blandit in nam, leo bibendum porta rutrum tristique consequat integer, fringilla himenaeos morbi velit nisi justo eros posuere morbi velit cras inceptos nibh.</div>
  </div>
);

export default LoremIpsum;
